language: cpp

  
matrix:
  include:
  - env:
    - OCPN_TARGET=raspbian
    - OCPN_TARGET_ARCH=armhf
    - OCPN_TARGET_VERSION=9.4
    - OCPN_BRANCH=ci
    - OCPN_STABLE_REPO=kees-verruijt/ocpn-plugins-stable
    - OCPN_UNSTABLE_REPO=kees-verruijt/ocpn-plugins-unstable
    - DOCKER_IMAGE=raspbian/stretch
    services:
    - docker
    script:
    - "./ci/travis-build-raspbian-armhf.sh"
  - env:
    - OCPN_TARGET=raspbian
    - OCPN_TARGET_ARCH=armhf
    - OCPN_TARGET_VERSION=10
    - OCPN_BRANCH=ci
    - OCPN_STABLE_REPO=kees-verruijt/ocpn-plugins-stable
    - OCPN_UNSTABLE_REPO=kees-verruijt/ocpn-plugins-unstable
    - DOCKER_IMAGE=opencpn/raspbian-buster:plugin_build_tooling
    services:
    - docker
    script:
    - "./ci/travis-build-raspbian-armhf.sh"


branches:
  only:
    - ci

