---
version: 2.1

debian-steps: &debian-steps
  steps:
    - checkout
    - run: ci/circleci-build-debian.sh
    - run: ci/circleci-upload.sh

jobs:
   build-xenial:
     docker:
       - image: circleci/buildpack-deps:xenial-scm
     environment:
       - OCPN_TARGET:  xenial
     <<: *debian-steps
   build-bionic:
     docker:
       - image: circleci/buildpack-deps:bionic-scm
     environment:
       - OCPN_TARGET:  bionic
     <<: *debian-steps
   build-focal:
     docker:
       - image: circleci/buildpack-deps:focal-scm
     environment:
       - OCPN_TARGET:  focal
     <<: *debian-steps
   build-buster:
     docker:
       - image: circleci/buildpack-deps:buster-scm
     environment:
       - OCPN_TARGET:  buster
     <<: *debian-steps
   build-flatpak:
     machine:
       image: ubuntu-1604:201903-01
     environment:
       - OCPN_TARGET:  flatpak
     steps:
       - checkout
       - run: ci/circleci-build-flatpak.sh
       - run: ci/circleci-upload.sh
   build-mingw:
     docker:
       - image: fedora:33
     environment:
       - OCPN_TARGET: mingw
     steps:
       - run: su -c "dnf install -q -y git openssh-clients openssh-server"
       - checkout
       - run: ci/circleci-build-mingw.sh
       - run: ci/circleci-upload.sh
   build-macos:
     macos:
       xcode: "11.3.0"
     environment:
       - OCPN_TARGET:  macos
     steps:
       - checkout
       - restore_cache:
          keys:
            - macos-cache-v1-{{checksum "ci/circleci-build-macos.sh"}}
       - run: ci/circleci-build-macos.sh
       - save_cache:
          key: macos-cache-v1-{{checksum "ci/circleci-build-macos.sh"}}
          paths:
            - /usr/local/Homebrew
            - /usr/local/Caskroom
            - /usr/local/Cellar
            - /usr/local/bin
            - /usr/local/include
            - /usr/local/lib
            - /usr/local/opt
       - run: ci/circleci-upload.sh

std-filters: &std-filters
  filters:
    branches:
      only:
        - master
        - beta

workflows:
  version: 2
  build_all:
    jobs:
      - build-buster:
          <<: *std-filters
      - build-xenial:
          <<: *std-filters
      - build-bionic:
          <<: *std-filters
      - build-focal:
          <<: *std-filters
      - build-flatpak:
          <<: *std-filters
      - build-macos:
          <<: *std-filters
      - build-mingw:
          <<: *std-filters
